interface=eth1
interface=eth2
bind-interfaces
no-hosts
no-resolv
domain-needed
enable-ra
log-dhcp
log-facility=-
dhcp-range=set:slaac,2001:db8:a1de:10::,ra-only,64,12h
dhcp-range=set:managed,2001:db8:a1de:20::100,2001:db8:a1de:20::1ff,64,10m
dhcp-option=tag:slaac,option6:dns-server,[2001:db8:a1de:10::1]
dhcp-option=tag:managed,option6:dns-server,[2001:db8:a1de:20::1]
host-record=router.lab.example,2001:db8:a1de:10::1
ra-param=eth1,5,45
ra-param=eth2,5,45
