# Start only on the isolated rogue node when instructed in README.
port=0
interface=eth1
bind-interfaces
enable-ra
no-hosts
no-resolv
log-dhcp
log-facility=-
dhcp-range=2001:db8:a1de:ee::,ra-only,64,2m
ra-param=eth1,high,5,45
