configure terminal
ip prefix-list HUB-ORIGIN seq 10 permit 10.29.0.0/16
ip prefix-list HUB-ORIGIN seq 20 permit 10.29.1.0/24
ip prefix-list HUB-ORIGIN seq 30 permit 0.0.0.0/0
route-map HUB-ORIGIN permit 10
 match ip address prefix-list HUB-ORIGIN
exit
ip prefix-list SPOKE-ROUTES seq 10 permit 10.29.2.0/24
ip prefix-list SPOKE-ROUTES seq 20 permit 10.29.3.0/24
route-map SPOKE-ROUTES permit 10
 match ip address prefix-list SPOKE-ROUTES
exit
route-map DENY-ALL deny 10
exit
ip route 10.29.0.0/16 Null0 254
ip route 0.0.0.0/0 Null0 254
router bgp 64501
 neighbor 10.29.255.6 remote-as 64500
 address-family ipv4 unicast
  neighbor 10.29.255.6 activate
  neighbor 10.29.255.6 route-map SPOKE-ROUTES in
  neighbor 10.29.255.6 route-map DENY-ALL out
  neighbor 10.29.255.6 maximum-prefix 8 75 restart 1
 exit-address-family
 address-family ipv4 unicast
  network 10.29.0.0/16
  network 0.0.0.0/0
  neighbor 10.29.255.0 route-map HUB-ORIGIN out
  neighbor 10.29.255.0 route-map DENY-ALL in
 exit-address-family
exit
end
