configure terminal
hostname ce2
ip prefix-list OWN seq 10 permit 10.29.2.0/24
route-map OWN permit 10
 match ip address prefix-list OWN
exit
ip prefix-list REMOTE seq 10 permit 10.29.1.0/24
ip prefix-list REMOTE seq 20 permit 10.29.3.0/24
ip prefix-list REMOTE seq 30 permit 10.29.0.0/16
ip prefix-list REMOTE seq 40 permit 0.0.0.0/0
route-map REMOTE permit 10
 match ip address prefix-list REMOTE
exit
router bgp 64501
 bgp router-id 10.29.2.1
 no bgp default ipv4-unicast
 neighbor 10.29.255.2 remote-as 64500
 address-family ipv4 unicast
  neighbor 10.29.255.2 activate
  neighbor 10.29.255.2 route-map REMOTE in
  neighbor 10.29.255.2 route-map OWN out
  neighbor 10.29.255.2 maximum-prefix 8 75 restart 1
 exit-address-family
 address-family ipv4 unicast
  network 10.29.2.0/24
 exit-address-family
exit
end
