configure terminal
hostname p1
router isis CORE
 is-type level-2-only
 net 49.0029.0000.0000.0009.00
 metric-style wide
 lsp-gen-interval 1
 spf-interval 1
exit
interface lo
 ip router isis CORE
 isis passive
exit
interface eth1
 ip router isis CORE
 isis network point-to-point
 isis circuit-type level-2-only
 isis hello-interval 1
 isis hello-multiplier 3
exit
interface eth2
 ip router isis CORE
 isis network point-to-point
 isis circuit-type level-2-only
 isis hello-interval 1
 isis hello-multiplier 3
exit
mpls ldp
 router-id 10.255.0.9
 address-family ipv4
  discovery transport-address 10.255.0.9
  interface eth1
  exit
  interface eth2
  exit
 exit-address-family
exit
end
