configure terminal
ip prefix-list HUB-IN seq 10 permit 10.29.0.0/16
ip prefix-list HUB-IN seq 20 permit 10.29.1.0/24
ip prefix-list HUB-IN seq 30 permit 0.0.0.0/0
route-map HUB-IN permit 10
 match ip address prefix-list HUB-IN
exit
ip prefix-list HUB-PRIVATE seq 10 permit 10.29.0.0/16
ip prefix-list HUB-PRIVATE seq 20 permit 10.29.1.0/24
route-map HUB-PRIVATE permit 10
 match ip address prefix-list HUB-PRIVATE
exit
ip prefix-list HUB-DEFAULT seq 10 permit 0.0.0.0/0
route-map HUB-DEFAULT permit 10
 match ip address prefix-list HUB-DEFAULT
exit
ip prefix-list SPOKE-ROUTES seq 10 permit 10.29.2.0/24
ip prefix-list SPOKE-ROUTES seq 20 permit 10.29.3.0/24
route-map SPOKE-ROUTES permit 10
 match ip address prefix-list SPOKE-ROUTES
exit
route-map DENY-ALL deny 10
exit
route-map HUB-EXPORT permit 10
 match ip address prefix-list HUB-DEFAULT
 set extcommunity rt 64500:2999
exit
route-map HUB-EXPORT permit 20
 match ip address prefix-list HUB-PRIVATE
 set extcommunity rt 64500:2911
exit
router bgp 64500 vrf site1
 address-family ipv4 unicast
  no rt vpn import 64500:2900
  no rt vpn export 64500:2900
  no route-map vpn export SITE1-IN
  route-map vpn export HUB-EXPORT
  neighbor 10.29.255.1 route-map HUB-IN in
  neighbor 10.29.255.1 route-map DENY-ALL out
 exit-address-family
exit
router bgp 64500 vrf hub-return
 bgp router-id 10.255.0.1
 no bgp default ipv4-unicast
 neighbor 10.29.255.7 remote-as 64501
 address-family ipv4 unicast
  neighbor 10.29.255.7 activate
  neighbor 10.29.255.7 route-map DENY-ALL in
  neighbor 10.29.255.7 route-map SPOKE-ROUTES out
  neighbor 10.29.255.7 maximum-prefix 8 75 restart 1
 exit-address-family
 address-family ipv4 unicast
  neighbor 10.29.255.7 as-override
  rd vpn export 10.255.0.1:101
  rt vpn import 64500:2912
  import vpn
 exit-address-family
exit
end
