configure terminal
router bgp 64500 vrf site2
 address-family ipv4 unicast
  no rt vpn import 64500:2900
  no rt vpn export 64500:2900
  rt vpn import 64500:2911 64500:2999
  rt vpn export 64500:2912
 exit-address-family
exit
router bgp 64500 vrf site3
 address-family ipv4 unicast
  no rt vpn import 64500:2900
  no rt vpn export 64500:2900
  rt vpn import 64500:2911
  rt vpn export 64500:2912
 exit-address-family
exit
end
