configure terminal
evpn mh startup-delay 3
interface bond30
 evpn mh es-id 30
 evpn mh es-sys-mac 02:00:30:ee:00:04
 evpn mh es-df-pref 100
exit
interface eth1
 evpn mh uplink
exit
interface eth2
 evpn mh uplink
exit
end
