configure terminal
router bgp 64500
 bgp router-id 10.255.0.11
 no bgp default ipv4-unicast
 bgp ebgp-requires-policy
 bgp network import-check
 neighbor 10.255.0.12 remote-as 64500
 neighbor 10.255.0.12 update-source lo
 neighbor 10.255.0.12 timers 3 9
 neighbor 10.255.0.21 remote-as 64500
 neighbor 10.255.0.21 update-source lo
 neighbor 10.255.0.21 timers 3 9
 neighbor 10.255.0.22 remote-as 64500
 neighbor 10.255.0.22 update-source lo
 neighbor 10.255.0.22 timers 3 9
 neighbor 10.255.0.23 remote-as 64500
 neighbor 10.255.0.23 update-source lo
 neighbor 10.255.0.23 timers 3 9
 address-family ipv4 unicast
  neighbor 10.255.0.12 activate
  neighbor 10.255.0.21 activate
  neighbor 10.255.0.22 activate
  neighbor 10.255.0.23 activate
 exit-address-family
end
