configure terminal
ip prefix-list IMPORT seq 10 permit 198.18.0.0/24
route-map IMPORT permit 10
 match ip address prefix-list IMPORT
exit
ip prefix-list EXPORT seq 10 permit 203.0.113.0/24
route-map EXPORT permit 10
 match ip address prefix-list EXPORT
exit
router bgp 64500
 bgp router-id 10.255.0.21
 no bgp default ipv4-unicast
 bgp ebgp-requires-policy
 bgp network import-check
 neighbor 10.255.0.11 remote-as 64500
 neighbor 10.255.0.11 update-source lo
 neighbor 10.255.0.11 timers 3 9
 neighbor 10.255.0.12 remote-as 64500
 neighbor 10.255.0.12 update-source lo
 neighbor 10.255.0.12 timers 3 9
 neighbor 192.0.2.1 remote-as 64496
 neighbor 192.0.2.1 timers 3 9
 address-family ipv4 unicast
  neighbor 10.255.0.11 activate
  neighbor 10.255.0.11 next-hop-self
  neighbor 10.255.0.12 activate
  neighbor 10.255.0.12 next-hop-self
  neighbor 192.0.2.1 activate
  neighbor 192.0.2.1 route-map IMPORT in
  neighbor 192.0.2.1 route-map EXPORT out
 exit-address-family
end
