configure terminal
ip prefix-list IMPORT seq 10 permit 203.0.113.0/24
route-map IMPORT permit 10
 match ip address prefix-list IMPORT
exit
ip prefix-list EXPORT seq 10 permit 198.18.0.0/24
route-map EXPORT permit 10
 match ip address prefix-list EXPORT
exit
ip route 198.18.0.0/24 blackhole
router bgp 64496
 bgp router-id 10.96.0.1
 no bgp default ipv4-unicast
 bgp ebgp-requires-policy
 bgp network import-check
 neighbor 192.0.2.0 remote-as 64500
 neighbor 192.0.2.0 timers 3 9
 address-family ipv4 unicast
  network 198.18.0.0/24
  neighbor 192.0.2.0 activate
  neighbor 192.0.2.0 route-map IMPORT in
  neighbor 192.0.2.0 route-map EXPORT out
 exit-address-family
end
