frr version 10.2
frr defaults traditional
hostname pe1
!
router ospf
 ospf router-id 10.255.0.1
 network 10.255.0.1/32 area 0
 network 10.254.0.0/31 area 0
!
mpls ldp
 router-id 10.255.0.1
 address-family ipv4
  discovery transport-address 10.255.0.1
  interface eth1
 exit-address-family
!
router bgp 64500
 bgp router-id 10.255.0.1
 no bgp default ipv4-unicast
 neighbor 10.255.0.2 remote-as 64500
 neighbor 10.255.0.2 update-source lo
 address-family ipv4 vpn
  neighbor 10.255.0.2 activate
 exit-address-family
!
ip prefix-list CUST-A-EXPORT seq 10 permit 10.101.0.0/24
!
route-map CUST-A-EXPORT permit 10
 match ip address prefix-list CUST-A-EXPORT
route-map CUST-A-EXPORT deny 100
!
router bgp 64500 vrf CUST-A
 bgp router-id 10.255.0.1
 address-family ipv4 unicast
  redistribute connected
  rd vpn export 10.255.0.1:1001
  label vpn export auto
  rt vpn export 64500:1001
  rt vpn import 64500:1001 64500:9000
  route-map vpn export CUST-A-EXPORT
  export vpn
  import vpn
 exit-address-family
!
ip prefix-list CUST-B-EXPORT seq 10 permit 10.102.0.0/24
!
route-map CUST-B-EXPORT permit 10
 match ip address prefix-list CUST-B-EXPORT
route-map CUST-B-EXPORT deny 100
!
router bgp 64500 vrf CUST-B
 bgp router-id 10.255.0.1
 address-family ipv4 unicast
  redistribute connected
  rd vpn export 10.255.0.1:1002
  label vpn export auto
  rt vpn export 64500:1002
  rt vpn import 64500:1002 64500:9000
  route-map vpn export CUST-B-EXPORT
  export vpn
  import vpn
 exit-address-family
!
ip prefix-list CUST-C-EXPORT seq 10 permit 10.103.0.0/24
!
route-map CUST-C-EXPORT permit 10
 match ip address prefix-list CUST-C-EXPORT
route-map CUST-C-EXPORT deny 100
!
router bgp 64500 vrf CUST-C
 bgp router-id 10.255.0.1
 address-family ipv4 unicast
  redistribute connected
  rd vpn export 10.255.0.1:1003
  label vpn export auto
  rt vpn export 64500:1003
  rt vpn import 64500:1003 64500:9000
  route-map vpn export CUST-C-EXPORT
  export vpn
  import vpn
 exit-address-family
!
