port=0
interface=eth1
bind-interfaces
no-resolv
no-hosts
log-facility=-
log-dhcp
dhcp-authoritative
dhcp-range=10.10.0.100,10.10.0.150,255.255.252.0,10m
dhcp-option=option:router,10.10.0.1
dhcp-option=option:dns-server,10.10.14.10
dhcp-option=option:ntp-server,10.10.14.10
