configure terminal
hostname ix-peer
ip prefix-list IMPORT seq 10 permit 203.0.113.0/24
ip prefix-list IMPORT seq 20 permit 198.18.255.0/24
ip prefix-list ANNOUNCE seq 10 permit 198.51.100.128/25
route-map IMPORT permit 10
 match ip address prefix-list IMPORT
exit
route-map IMPORT deny 100
exit
route-map ANNOUNCE permit 10
 match ip address prefix-list ANNOUNCE
exit
route-map ANNOUNCE deny 100
exit
ip route 198.51.100.128/25 blackhole
router bgp 64498
 bgp router-id 10.98.0.1
 no bgp default ipv4-unicast
 bgp ebgp-requires-policy
 bgp network import-check
 neighbor 198.51.100.0 remote-as 64500
 neighbor 198.51.100.0 timers 3 9
 neighbor 198.51.100.0 timers connect 1
 neighbor 198.51.100.0 local-role peer strict-mode
 address-family ipv4 unicast
  network 198.51.100.128/25
  neighbor 198.51.100.0 activate
  neighbor 198.51.100.0 route-map IMPORT in
  neighbor 198.51.100.0 route-map ANNOUNCE out
  neighbor 198.51.100.0 send-community all
  neighbor 198.51.100.0 soft-reconfiguration inbound
  neighbor 198.51.100.0 maximum-prefix 16 75
 exit-address-family
end
