configure terminal
hostname customer
ip prefix-list OWN seq 10 permit 203.0.113.0/24
route-map EXPORT permit 10
 match ip address prefix-list OWN
exit
route-map IMPORT deny 10
exit
ip route 203.0.113.0/24 Null0
router bgp 64501
 bgp router-id 192.0.2.1
 neighbor 192.0.2.0 remote-as 64500
 address-family ipv4 unicast
  network 203.0.113.0/24
  neighbor 192.0.2.0 activate
  neighbor 192.0.2.0 route-map IMPORT in
  neighbor 192.0.2.0 route-map EXPORT out
 exit-address-family
exit
end
