configure terminal
hostname neighbour
ip prefix-list OWN seq 10 permit 198.51.100.0/24
ip prefix-list ATTACK seq 10 permit 203.0.113.128/25
route-map EXPORT permit 10
 match ip address prefix-list OWN
exit
route-map IMPORT deny 10
exit
ip route 198.51.100.0/24 Null0
router bgp 64502
 bgp router-id 192.0.2.3
 neighbor 192.0.2.2 remote-as 64500
 address-family ipv4 unicast
  network 198.51.100.0/24
  neighbor 192.0.2.2 activate
  neighbor 192.0.2.2 route-map IMPORT in
  neighbor 192.0.2.2 route-map EXPORT out
 exit-address-family
exit
end
