global_defs {
 router_id LAB13_R2
 vrrp_version 3
}
vrrp_sync_group BOTH_LANS {
 group {
  CLIENT
  SERVER
 }
}
vrrp_instance CLIENT {
 state BACKUP
 interface eth1
 virtual_router_id 110
 priority 100
 advert_int 1
 use_vmac
 no_accept
 virtual_ipaddress {
  10.10.0.1/22
 }
}
vrrp_instance SERVER {
 state BACKUP
 interface eth2
 virtual_router_id 113
 priority 100
 advert_int 1
 use_vmac
 no_accept
 virtual_ipaddress {
  198.51.100.1/24
 }
}
