configure terminal
hostname rp
router ospf
 ospf router-id 10.255.0.4
exit
interface lo
 ip ospf area 0
 ip ospf passive
 ip pim
exit
interface eth1
 ip ospf area 0
 ip pim
 ip ospf network point-to-point
exit
ip prefix-list SSM seq 10 permit 232.0.0.0/8 le 32
router pim
 rp 10.255.0.4 239.0.0.0/8
 ssm prefix-list SSM
 rpf-lookup-mode urib-only
exit
end
