configure terminal
hostname r2
router isis CORE
 is-type level-2-only
 net 49.0001.0000.0000.0002.00
 metric-style wide
 topology ipv6-unicast
 lsp-gen-interval 1
 spf-interval 1
exit
interface lo
 ipv6 router isis CORE
 isis passive
exit
interface eth1
 ipv6 router isis CORE
 isis circuit-type level-2-only
 isis network point-to-point
 isis topology ipv6-unicast
 isis metric 10
 isis hello-interval 1
 isis hello-multiplier 3
exit
interface eth2
 ipv6 router isis CORE
 isis circuit-type level-2-only
 isis network point-to-point
 isis topology ipv6-unicast
 isis metric 10
 isis hello-interval 1
 isis hello-multiplier 3
exit
end
