#!/usr/bin/env python3
"""Lab 52.2 --- TACACS+ does not encrypt, and the difference is executable.

WHY THIS LAB EXISTS
-------------------
The chapter presented TACACS+ as the better choice for device administration
because it "encrypts the whole payload" where RADIUS encrypts only the password.
That comparison omits transport and attribute details. Legacy TACACS+ body
obfuscation, legacy RADIUS attribute protection and secure transports must be
assessed separately; this lab does not implement a RADIUS comparison.

TACACS+ applies an OBFUSCATION, not encryption. RFC 8907, which documents the
protocol as it is deployed, says so in those terms and describes the mechanism
as deprecated, insecure, and to be run inside a secure transport such as TLS.
The construction is a keystream generated by chaining MD5 over the session id,
the shared key, the version and the sequence number, XORed over the body.

Three consequences follow, and this lab executes all three:

  THE KEYSTREAM DEPENDS ON NOTHING SECRET-PER-MESSAGE.  It is a function of
  (session id, key, version, sequence number) alone. Two bodies carried under
  the same session id, key, version and sequence number use the SAME pad, so an
  attacker who knows one recovers the other exactly --- the identical failure
  as repeated keystream use. Repeated inputs are an explicit scenario, not
  proof that every real exchange repeats its pad.

  THE BODY IS MALLEABLE.  XOR of a keystream gives a one-to-one relation
  between ciphertext and plaintext bits, so an attacker who knows the format
  edits the body to a chosen value without the key --- authorisation results
  included in this synthetic ASCII demonstration; no valid wire reply or
  client acceptance is implemented.

  AND THERE IS NO INTEGRITY FIELD AT ALL.  The header carries a length, not a
  message authentication code, so an edited body arrives looking exactly as
  valid as an honest one.

    python3 tacacs_obfuscation.py
    python3 tacacs_obfuscation.py --json
    python3 test_tacacs_obfuscation.py

LINUX EXECUTION of the construction, in this file, against bodies this file
makes up. NO TACACS+ server, client, device or capture was involved, nothing
was sent anywhere, and no real shared secret exists. This demonstrates a
property of the published construction; it is not an attack on any deployment,
and every byte below is synthetic. The ASCII bodies are not parsed TACACS+
wire replies; successful string manipulation does not prove a real client
would accept an altered authorisation response.
"""
import argparse
import hashlib
import json
import struct
import sys
import textwrap


class TacacsError(ValueError):
    """The described obfuscation cannot be carried out."""


# ---------------------------------------------------------------------------
# the construction, from the published description
# ---------------------------------------------------------------------------
def pseudo_pad(session_id, key, version, seq_no, length):
    """The keystream: MD5 chained over session id, key, version and sequence.

    Note what is absent from the inputs: anything that varies per message
    beyond the sequence number, and anything secret that either party chose
    freshly. That absence is the whole of this lab.
    """
    if not isinstance(key, (bytes, bytearray)) or not key:
        raise TacacsError('a shared key is required')
    if not 0 <= session_id <= 0xFFFFFFFF:
        raise TacacsError('session id must fit in 32 bits, got %r' % session_id)
    if not 0 <= version <= 0xFF:
        raise TacacsError('version must be one byte, got %r' % version)
    if not 0 <= seq_no <= 0xFF:
        raise TacacsError('sequence number must be one byte, got %r' % seq_no)
    if length < 0:
        raise TacacsError('length cannot be negative')
    base = struct.pack('!I', session_id) + bytes(key) + bytes([version]) + \
        bytes([seq_no])
    out, prev = b'', b''
    while len(out) < length:
        prev = hashlib.md5(base + prev).digest()
        out += prev
    return out[:length]


def obfuscate(session_id, key, version, seq_no, body):
    """XOR the body with the pad. Deobfuscation is the same operation."""
    pad = pseudo_pad(session_id, key, version, seq_no, len(body))
    return bytes(a ^ b for a, b in zip(body, pad))


deobfuscate = obfuscate


def edit_without_key(blob, offset, known, desired):
    """Change an obfuscated body to a chosen plaintext, holding no key."""
    if len(known) != len(desired):
        raise TacacsError('an XOR edit cannot change the length: %d against %d'
                          % (len(known), len(desired)))
    if offset < 0 or offset + len(known) > len(blob):
        raise TacacsError('edit runs past the end of the body')
    out = bytearray(blob)
    for i, (k, d) in enumerate(zip(known, desired)):
        out[offset + i] ^= k ^ d
    return bytes(out)


# ---------------------------------------------------------------------------
# synthetic bodies. Nothing here came off a wire.
# ---------------------------------------------------------------------------
AUTHOR_REQUEST = b'user=jsmith    cmd=show    cmd-arg=running-config  '
AUTHOR_REPLY_DENY = b'status=FAIL   msg=command not permitted for role  '
AUTHOR_REPLY_PASS = b'status=PASS   msg=command permitted by policy     '


def demo_round_trip():
    key = b'a-shared-secret-nobody-rotated'
    blob = obfuscate(0x11223344, key, 0xC0, 1, AUTHOR_REQUEST)
    back = deobfuscate(0x11223344, key, 0xC0, 1, blob)
    return {'round_trip_exact': back == AUTHOR_REQUEST,
            'body_length': len(AUTHOR_REQUEST),
            'blob_length': len(blob),
            'length_unchanged': len(blob) == len(AUTHOR_REQUEST),
            'note': 'Same operation both ways, because XOR is its own inverse. '
                    'The length is unchanged, which is already a leak: an '
                    'observer counts the bytes of every request and reply.'}


def demo_pad_reuse():
    """Two bodies at the same session and sequence share a pad, exactly."""
    key = b'a-shared-secret-nobody-rotated'
    sid, ver, seq = 0x11223344, 0xC0, 1
    a = obfuscate(sid, key, ver, seq, AUTHOR_REPLY_DENY)
    b = obfuscate(sid, key, ver, seq, AUTHOR_REPLY_PASS[:len(AUTHOR_REPLY_DENY)])
    # The attacker knows one body --- a denial is the common case and its text
    # is fixed by the implementation --- and holds both blobs.
    recovered = bytes(x ^ y ^ z for x, y, z in zip(a, b, AUTHOR_REPLY_DENY))
    return {
        'attacker_knew': AUTHOR_REPLY_DENY.decode().strip(),
        'attacker_recovered': recovered.decode('latin-1').strip(),
        'recovery_exact': recovered == AUTHOR_REPLY_PASS[:len(AUTHOR_REPLY_DENY)],
        'key_used_by_attacker': False,
        'why': 'The pad is a function of (session id, key, version, sequence) '
               'and nothing else, so any two bodies sharing those four share a '
               'keystream. This is not a nonce someone reused; it is what the '
               'construction does.',
    }


def demo_malleable():
    key = b'a-shared-secret-nobody-rotated'
    sid, ver, seq = 0x55667788, 0xC0, 2
    blob = obfuscate(sid, key, ver, seq, AUTHOR_REPLY_DENY)
    off = AUTHOR_REPLY_DENY.index(b'FAIL')
    edited = edit_without_key(blob, off, b'FAIL', b'PASS')
    seen = deobfuscate(sid, key, ver, seq, edited)
    return {
        'original': AUTHOR_REPLY_DENY.decode().strip(),
        'what_the_device_now_reads': seen.decode('latin-1').strip(),
        'bytes_changed': sum(1 for x, y in zip(blob, edited) if x != y),
        'length_unchanged': len(edited) == len(blob),
        'key_used_by_attacker': False,
        'integrity_field_present': False,
        'why': 'XOR gives a one-to-one relation between ciphertext and '
               'plaintext bits, so knowing the format is enough to choose the '
               'result. The header carries a length, not a MAC, so nothing '
               'downstream can tell.',
    }


def demo_pad_is_deterministic():
    """The same four inputs always give the same pad --- checked, not assumed."""
    key = b'a-shared-secret-nobody-rotated'
    p1 = pseudo_pad(0x11223344, key, 0xC0, 1, 64)
    p2 = pseudo_pad(0x11223344, key, 0xC0, 1, 64)
    diff_seq = pseudo_pad(0x11223344, key, 0xC0, 2, 64)
    diff_sid = pseudo_pad(0x11223345, key, 0xC0, 1, 64)
    diff_key = pseudo_pad(0x11223344, key + b'x', 0xC0, 1, 64)
    return {
        'same_inputs_same_pad': p1 == p2,
        'sequence_changes_pad': p1 != diff_seq,
        'session_changes_pad': p1 != diff_sid,
        'key_changes_pad': p1 != diff_key,
        'pad_is_a_prefix_of_itself': pseudo_pad(0x11223344, key, 0xC0, 1, 32)
                                     == p1[:32],
    }


def build_report():
    return {
        'executed': {
            'round_trip': demo_round_trip(),
            'determinism': demo_pad_is_deterministic(),
            'pad_reuse': demo_pad_reuse(),
            'malleable': demo_malleable(),
        },
        'evidence_category':
            'LINUX EXECUTION of the published construction, on synthetic bodies '
            'invented in this file. NO TACACS+ server, client, device or packet '
            'capture was involved and nothing was sent anywhere.',
        'what_it_is_not': [
            'Not an attack on any deployment. Every byte is synthetic and no '
            'real shared secret exists anywhere in this file.',
            'Not a claim that RADIUS is better. RADIUS obfuscates only the '
            'password attribute and leaves the rest in clear, which is worse '
            'on this axis; the chapter\'s preference for TACACS+ in device '
            'administration stands. What changes is the word used for what it '
            'provides, and therefore what you must add.',
            'Not a statement about TACACS+ over TLS. The published document '
            'recommends exactly that, and a TLS-wrapped session does not have '
            'the properties demonstrated here --- which is the point: the '
            'transport supplies them, not the protocol.',
            'Not a complete protocol model. Headers, packet framing, sequence '
            'handling, single-connection mode and the authentication and '
            'accounting exchanges are all absent.',
        ],
        'caveats': [
            'The attacker in the pad-reuse demonstration is assumed to know '
            'one body. For a fixed-format reply such as a denial that is a '
            'reasonable assumption and not a cryptographic break.',
            'The attacker in the malleability demonstration is assumed to know '
            'the offset of the field being changed, which again follows from '
            'the format rather than from any secret.',
            'An on-path position is assumed throughout. Obtaining one is a '
            'separate problem this lab says nothing about --- and is exactly '
            'what the out-of-band network exists to make harder.',
            'MD5 is used here because the construction specifies it. Nothing '
            'in this lab depends on any weakness of MD5: the failures shown '
            'are properties of a keystream XOR with no per-message secret and '
            'no integrity field, and substituting a stronger hash changes none '
            'of them.',
        ],
    }


def _wrap(lines, text, indent='  '):
    lines.extend(textwrap.wrap(text, width=74, initial_indent=indent,
                               subsequent_indent=indent))


def report_text(rep):
    e = rep['executed']
    L = []
    L.append('TACACS+ obfuscation, executed (Chapter 52)')
    L.append('Synthetic bodies only. No server, client, device or capture.')
    L.append('')
    L.append('A. The construction, and what is missing from its inputs')
    L.append('-' * 74)
    d = e['determinism']
    L.append('  same four inputs give the same pad   %s' % d['same_inputs_same_pad'])
    L.append('  changing the sequence changes it     %s' % d['sequence_changes_pad'])
    L.append('  changing the session changes it      %s' % d['session_changes_pad'])
    L.append('  changing the key changes it          %s' % d['key_changes_pad'])
    r = e['round_trip']
    L.append('  round trip exact                     %s' % r['round_trip_exact'])
    L.append('  body length unchanged by the process %s' % r['length_unchanged'])
    L.append('')
    _wrap(L, 'The pad is a function of the session id, the shared key, the '
             'version and the sequence number. Nothing else. No party '
             'contributes a fresh secret per message, and the length is '
             'preserved, so an observer already counts the bytes of every '
             'request and reply.')
    L.append('')
    L.append('B. Two bodies, one pad')
    L.append('-' * 74)
    p = e['pad_reuse']
    L.append('  attacker knew       %s' % p['attacker_knew'])
    L.append('  attacker recovered  %s' % p['attacker_recovered'])
    L.append('  recovery exact: %s,  key used: %s'
             % (p['recovery_exact'], p['key_used_by_attacker']))
    L.append('')
    _wrap(L, p['why'])
    L.append('')
    L.append('C. Editing the answer')
    L.append('-' * 74)
    m = e['malleable']
    L.append('  the server said            %s' % m['original'])
    L.append('  the device now reads       %s' % m['what_the_device_now_reads'])
    L.append('  bytes changed %d, length unchanged %s, key used %s'
             % (m['bytes_changed'], m['length_unchanged'],
                m['key_used_by_attacker']))
    L.append('  integrity field present    %s' % m['integrity_field_present'])
    L.append('')
    _wrap(L, m['why'])
    L.append('')
    _wrap(L, 'A denial became a permission: %d byte%s changed, no key, and '
             'nothing in the protocol to notice --- which is why the published '
             'document calls the mechanism deprecated and insecure and tells '
             'you to run it inside a secure transport. (Note the count: '
             'FAIL and PASS share a letter, so only %d of the four positions '
             'needed touching. The edit is bounded by the difference between '
             'the words, not by their length.)'
             % (m['bytes_changed'], '' if m['bytes_changed'] == 1 else 's',
                m['bytes_changed']))
    L.append('')
    L.append('D. What this does and does not change about the advice')
    L.append('-' * 74)
    for x in rep['what_it_is_not']:
        L.extend(textwrap.wrap(x, width=74, initial_indent='- ',
                               subsequent_indent='  '))
    L.append('')
    _wrap(L, 'So keep TACACS+ for device administration and stop calling it '
             'encrypted. What you are relying on is the shared key staying '
             'secret AND the path staying trustworthy --- which makes the '
             'out-of-band network part of the cryptography rather than a '
             'convenience, and makes TLS transport the fix rather than a '
             'refinement.')
    L.append('')
    L.append('What this does NOT establish')
    L.append('-' * 74)
    for c in rep['caveats']:
        L.extend(textwrap.wrap(c, width=74, initial_indent='- ',
                               subsequent_indent='  '))
    return '\n'.join(L)


def main(argv=None):
    p = argparse.ArgumentParser(description=__doc__.split('\n')[0])
    p.add_argument('--json', action='store_true', help='emit the report as JSON')
    a = p.parse_args(argv)
    try:
        rep = build_report()
    except TacacsError as exc:
        print('cannot evaluate: %s' % exc, file=sys.stderr)
        return 2
    print(json.dumps(rep, indent=2) if a.json else report_text(rep))
    return 0


if __name__ == '__main__':
    sys.exit(main())
