configure terminal
hostname lds-p-02
router isis CORE
 is-type level-2-only
 net 49.0001.0102.5500.0015.00
 metric-style wide
 topology ipv6-unicast
 domain-password md5 LAB20-DEMO-ONLY authenticate snp validate
 lsp-gen-interval 1
 spf-interval 1
 log-adjacency-changes
 log-pdu-drops
exit
interface lo
 ip router isis CORE
 ipv6 router isis CORE
 isis passive
exit
interface eth1
 ip router isis CORE
 ipv6 router isis CORE
 isis circuit-type level-2-only
 isis network point-to-point
 isis metric 40
 isis topology ipv6-unicast
 isis password md5 LAB20-DEMO-ONLY
 isis hello-interval 1
 isis hello-multiplier 3
exit
end
