configure terminal
hostname r-b1
key chain LAB19
 key 19
  key-string LAB19-DEMO-ONLY-DO-NOT-REUSE-2026
  cryptographic-algorithm hmac-sha-256
 exit
exit
interface eth1
 ip ospf area 2
 bandwidth 10000
 ip ospf network point-to-point
 ip ospf hello-interval 1
 ip ospf dead-interval 4
 ip ospf authentication key-chain LAB19
exit
interface lo
 ip ospf area 2
exit
router ospf
 ospf router-id 10.255.0.102
 auto-cost reference-bandwidth 400000
 passive-interface default
 no passive-interface eth1
exit
end
