configure terminal
hostname lon-pe-01
router isis CORE
 is-type level-2-only
 net 49.0001.0102.5500.0023.00
 metric-style wide
 lsp-gen-interval 1
 spf-interval 1
exit
interface lo
 ip router isis CORE
 isis passive
exit
interface eth1
 ip router isis CORE
 isis circuit-type level-2-only
 isis network point-to-point
 isis metric 40
 isis hello-interval 1
 isis hello-multiplier 3
exit
end
