configure terminal
hostname sel-a1
ip route 198.18.10.0/24 blackhole
ip prefix-list ONLY seq 10 permit 198.18.10.0/24
route-map ONLY permit 10
 match ip address prefix-list ONLY
 set metric 0
exit
route-map NONE deny 10
exit
router bgp 64496
 bgp router-id 10.96.0.3
 no bgp default ipv4-unicast
 bgp ebgp-requires-policy
 bgp network import-check
 neighbor 192.0.2.16 remote-as 64500
 neighbor 192.0.2.16 timers 3 9
 neighbor 192.0.2.16 timers connect 1
 neighbor 192.0.2.16 advertisement-interval 0
 address-family ipv4 unicast
  network 198.18.10.0/24
  neighbor 192.0.2.16 activate
  neighbor 192.0.2.16 route-map NONE in
  neighbor 192.0.2.16 route-map ONLY out
 exit-address-family
end
