configure terminal
hostname select
ip prefix-list ONLY seq 10 permit 198.18.10.0/24
route-map ONLY permit 10
 match ip address prefix-list ONLY
exit
route-map NONE deny 10
exit
router bgp 64500
 bgp router-id 10.255.21.1
 no bgp default ipv4-unicast
 bgp ebgp-requires-policy
 neighbor 192.0.2.17 remote-as 64496
 neighbor 192.0.2.17 timers 3 9
 neighbor 192.0.2.17 timers connect 1
 neighbor 192.0.2.17 advertisement-interval 0
 neighbor 192.0.2.17 shutdown
 neighbor 192.0.2.19 remote-as 64496
 neighbor 192.0.2.19 timers 3 9
 neighbor 192.0.2.19 timers connect 1
 neighbor 192.0.2.19 advertisement-interval 0
 neighbor 192.0.2.19 shutdown
 neighbor 192.0.2.21 remote-as 64497
 neighbor 192.0.2.21 timers 3 9
 neighbor 192.0.2.21 timers connect 1
 neighbor 192.0.2.21 advertisement-interval 0
 neighbor 192.0.2.21 shutdown
 address-family ipv4 unicast
  maximum-paths 1
  neighbor 192.0.2.17 activate
  neighbor 192.0.2.17 route-map ONLY in
  neighbor 192.0.2.17 route-map NONE out
  neighbor 192.0.2.19 activate
  neighbor 192.0.2.19 route-map ONLY in
  neighbor 192.0.2.19 route-map NONE out
  neighbor 192.0.2.21 activate
  neighbor 192.0.2.21 route-map ONLY in
  neighbor 192.0.2.21 route-map NONE out
 exit-address-family
end
